name: Push New Post

on:
  push:
    branches:
      - main

jobs:
  push-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add posts/*
          git commit -m "Add new post via GitHub Actions"
          git push
